validate -r date options passed, and point to docs
Example use-case:
  $ punch -r 16603 -c potus
  date: invalid date ‘16603’
  Error: Invalid date format: '16603'; See '--date' of date(1) for valid input

diff --git a/bin/punch b/bin/punch
--- a/bin/punch
+++ b/bin/punch
@@ -603,10 +603,17 @@ running() {
 # Is integer range [$1,$2] inclusive of $3
 isInclusiveOf() ( { (( $3 >= $1 )) && (( $3 <= $2 )); }; )
 
+_assertValidDateFormat() (
+  date --date="$1" > /dev/null || {
+    error "Invalid date format: '$1'; See '--date' of date(1) for valid input"
+    die $E_USAGE
+  }
+)
+
 # gets current running total within a given range
 rangeReport() {
     local rStart rEnd=-1
-    rStart="${OPT_RANGE/,*/}"
+    rStart="${OPT_RANGE/,*/}"; _assertValidDateFormat "$rStart"
     if [ "${OPT_RANGE/,/}" = "$OPT_RANGE" ];then
         (( OPT_QUIET )) ||
             printf \
@@ -615,7 +622,7 @@ rangeReport() {
         rStart="$(printf '%s 00:00' "$(date --iso-8601 --date="$rStart")")"
           rEnd="$(printf '%s 23:59' "$(date --iso-8601 --date="$rStart")")"
     else
-        rEnd="${OPT_RANGE/*,/}"
+        rEnd="${OPT_RANGE/*,/}"; _assertValidDateFormat "$rEnd"
         error "end range (from $rStart to $rEnd) not yet implemented!"
         die $E_ERROR
     fi
